version: '2'

services:
  db_foodtosave:
    image: 'postgres:13.1-alpine'
    container_name: db_foodtosave
    environment:
      - POSTGRES_USER=gabriel
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=foodtosave
    volumes:
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  cache:
    image: "redis:7.0-alpine"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  app:
    image: 'foodtosave-app:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_foodtosave:5432/foodtosave
      - SPRING_DATASOURCE_USERNAME=gabriel
      - SPRING_DATASOURCE_PASSWORD=123456
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=foodtosave
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db_foodtosave
      - cache